"""initial_tables

Revision ID: bad94140f2d5
Revises: 
Create Date: 2026-02-24 02:40:10.010008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad94140f2d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_site',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('site_id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('word',
    sa.Column('word_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('word_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('client_domain',
    sa.Column('domain_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('domain_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['client_site.site_id'], ),
    sa.PrimaryKeyConstraint('domain_id')
    )
    op.create_table('low_confidence_word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('initial_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_text', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.word_id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('reference_word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('correct_text', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.word_id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('site_session',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('session_created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('bot_score_initial', sa.Float(), nullable=True),
    sa.Column('bot_score_final', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['client_site.site_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('behavior_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('signals_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['site_session.session_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('challenge',
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ref_word_id', sa.Integer(), nullable=False),
    sa.Column('low_conf_word_id', sa.Integer(), nullable=False),
    sa.Column('bot_score', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('is_human_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['low_conf_word_id'], ['low_confidence_word.word_id'], ),
    sa.ForeignKeyConstraint(['ref_word_id'], ['reference_word.word_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['site_session.session_id'], ),
    sa.PrimaryKeyConstraint('challenge_id')
    )
    op.create_table('low_confidence_consensus',
    sa.Column('low_conf_word_id', sa.Integer(), nullable=False),
    sa.Column('top_candidate_text', sa.String(length=255), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['low_conf_word_id'], ['low_confidence_word.word_id'], ),
    sa.PrimaryKeyConstraint('low_conf_word_id')
    )
    op.create_table('attempt',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('reference_input_text', sa.String(length=255), nullable=True),
    sa.Column('reference_input_normalized', sa.String(length=255), nullable=True),
    sa.Column('low_conf_input_text', sa.String(length=255), nullable=True),
    sa.Column('low_conf_input_normalized', sa.String(length=255), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('signals_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.challenge_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('low_confidence_submission',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('low_conf_word_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('submitted_text', sa.String(length=255), nullable=False),
    sa.Column('normalized_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.attempt_id'], ),
    sa.ForeignKeyConstraint(['low_conf_word_id'], ['low_confidence_word.word_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('low_confidence_submission')
    op.drop_table('attempt')
    op.drop_table('low_confidence_consensus')
    op.drop_table('challenge')
    op.drop_table('behavior_log')
    op.drop_table('site_session')
    op.drop_table('reference_word')
    op.drop_table('low_confidence_word')
    op.drop_table('client_domain')
    op.drop_table('word')
    op.drop_table('client_site')
    # ### end Alembic commands ###
